@startuml

class Category

class Allergen

class User

class Report

class ToxicityRating

Category "1" -- "*" Allergen
User .. Report : > owns
Report "1" *-> "*" ToxicityRating
ToxicityRating -> "1" Allergen



@enduml