CREATE TABLE PUBLIC.VG_CATEGORIA (
  ID   CHAR(36)    NOT NULL,
  NOME VARCHAR(45) NOT NULL,
  CONSTRAINT pk_categoria PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX NOME_UNIQUE_INDEX_8
  ON PUBLIC.VG_CATEGORIA (NOME);
-- CREATE UNIQUE INDEX PRIMARY_KEY_8
-- ON PUBLIC.VG_CATEGORIA (ID);


CREATE TABLE PUBLIC.VG_ALLERGENE (
  ID           CHAR(36)    NOT NULL,
  ID_CATEGORIA CHAR(36) DEFAULT ''00000000-0000-0000-0000-000000000000'' NOT NULL,
  NOME         VARCHAR(45) NOT NULL,
  CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID),
  CONSTRAINT CONSTRAINT_335 FOREIGN KEY (ID_CATEGORIA) REFERENCES PUBLIC.VG_CATEGORIA (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX CONSTRAINT_INDEX_3
  ON PUBLIC.VG_ALLERGENE (NOME);
CREATE INDEX CONSTRAINT_INDEX_33
  ON PUBLIC.VG_ALLERGENE (ID_CATEGORIA);
-- CREATE UNIQUE INDEX PRIMARY_KEY_3
--  ON PUBLIC.VG_ALLERGENE (ID);


CREATE TABLE PUBLIC.VG_REPORT (
  ID             CHAR(36)    NOT NULL,
  DATA_CREAZIONE DATE        NOT NULL,
  NOME_SOGGETTO  VARCHAR(35) NOT NULL,
  CONSTRAINT VG_REPORT_PK PRIMARY KEY (ID)
);
-- CREATE UNIQUE INDEX PRIMARY_KEY_C
--  ON PUBLIC.VG_REPORT (ID);

CREATE TABLE PUBLIC.VG_REPORT_DATA (
  ID_REPORT    CHAR(36)      NOT NULL,
  ID_ALLERGENE CHAR(36)      NOT NULL,
  TOX          DECIMAL(3, 2) NOT NULL,
  CONSTRAINT VG_REPORT_DATA_PK PRIMARY KEY (ID_REPORT, ID_ALLERGENE),
  CONSTRAINT VG_REPORT_DATA_VG_ALLERGENE_FK FOREIGN KEY (ID_ALLERGENE) REFERENCES PUBLIC.VG_ALLERGENE (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT VG_REPORT_DATA_VG_REPORT_FK FOREIGN KEY (ID_REPORT) REFERENCES PUBLIC.VG_REPORT (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);
-- CREATE UNIQUE INDEX PRIMARY_KEY_5
--   ON PUBLIC.VG_REPORT_DATA (ID_REPORT, ID_ALLERGENE);
-- CREATE INDEX VG_REPORT_DATA_VG_ALLERGENE_FK_INDEX_5
-- ON PUBLIC.VG_REPORT_DATA (ID_ALLERGENE);

INSERT INTO PUBLIC.VG_CATEGORIA (ID, NOME) VALUES ('00000000-0000-0000-0000-000000000000', 'DEFAULT_CATEGORY');
